### ISSUE TITLE
Latest releases of gnome/gtk3 (libclutter/libmutter) and wayland require libmali-wayland.so updated symbols

### ISSUE THREAD

**Issue by digitalsanity** [hizukiayaka/rockchip-mali#1]
Missing symbols like: gbm_bo_get_offset

/usr/bin/Xwayland: symbol lookup error: /usr/bin/Xwayland: undefined symbol gbm_bo_get_offset

gnome-shell: symbol lookup error: /usr/lib/aarch64-linux-gnu/libmutter-2.so.0: undefined symbol: gbm_surface_create_with_modifiers

This is upstream at Khronos I'm sure and probably not implemented there yet..

**Comment by digitalsanity** [comment]
(tllim was asking for me)

**Comment by heiher** [comment]
Refer: https://hev.cc/2845.html

**Comment by hizukiayaka** [comment]
I have talked with a RK staff to add those symbols.
