### ISSUE TITLE
EGL/GLES acceleration with modesetting driver on xorg 1.20

### ISSUE THREAD

**Issue by digitalsanity** [hizukiayaka/rockchip-mali#2]
Testing with rock64 and rockpro64 here.

The armsoc driver has many problems with blocking/interrupts, all graphical updates are blocking the application many times a second -- you can see with firefox on YouTube how often it blocks when the abort script notices appear.

The modeset driver in xorg 1.20 works great, however .. with everything.  On Ubuntu cosmic-proposed anyway, even KDE plasma/kwin works great with compositing, and with the -wayland (and gbm?) driver installed, wayland+xwayland even works pretty well (except the 1.20 XWayland has the gbo symbol issues, I tested with the 1.19 XWayland binary) and wayland is very fast.

Here is how you can test .. in weston the rk3399, I can run 20x glmark2-es2-waylands at the same time and all have good performance and the desktop remains responsive.  With armsoc + x11, you can only run 5x for the same fps and responsiveness drops to unusable.

So with modeset in xorg, everything is great - even YouTube 1080p while moving the window around and in fullscreen.  It feels nearly as fast as my MacBook Pro.. and kwin/Qt have GPU access directly and it seems to work well (plasma compositing with modeset is great), and now GTK3/Gnome do also, through libclutter/libmutter, so GTK apps will work with modeset..  but have the missing gbo symbol from khr.  There's just no native GLES/EGL and glamoregl is crashing if used.

**Comment by hizukiayaka** [comment]
I don't want to support X...
